# ========================
# Run Mode
# ========================

runMode=local
platform=android


# ========================
# Sauce Labs Credentials
# ========================

username=your_username
accessKey=your_access_key
appiumBuild=Regression_Build


# ========================
# Android Remote
# ========================

platformNameAndroid=Android
deviceNameAndroid=Samsung Galaxy S24.*
platformVersion=15
automationNameAndroid=UiAutomator2
appAndroid=storage:filename=DemoApp-v1.0.0.apk
deviceOrientation=PORTRAIT
appiumVersion=3.0.0


# ========================
# iOS Remote
# ========================

platformNameIOS=iOS
deviceNameIOS=iPhone 15
automationNameIOS=XCUITest
appIOS=storage:filename=Runner.app


# ========================
# Local Android
# ========================

androidSimulatorName=Pixel_10


# ========================
# Local iOS
# ========================

iosSimulatorName=iPhone 17